const {chromium}=require(process.env.PLAYWRIGHT_PATH||'/home/anton/.nvm/versions/node/v24.21.0/lib/node_modules/openclaw/node_modules/playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const errors=[];
try{for(const n of [2,3,4]){const contexts=[],pages=[];try{for(let i=0;i<n;i++){const c=await browser.newContext({viewport:{width:1280,height:800}}),p=await c.newPage();contexts.push(c);pages.push(p);p.on('pageerror',e=>errors.push(e.message));if(process.env.SITE)await p.route('https://samsonovss.github.io/dust-turbo/**',async route=>{const file=new URL(route.request().url()).pathname.split('/').pop()||'index.html';if(fs.existsSync(process.env.SITE+'/'+file))await route.fulfill({path:process.env.SITE+'/'+file,contentType:file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html'});else await route.abort();});await p.goto('https://samsonovss.github.io/dust-turbo/?test='+Date.now(),{waitUntil:'domcontentloaded',timeout:60000});assert.equal(await p.locator('#mp-reconnect').count(),0);await p.locator('#friend').click();await p.waitForFunction(()=>DustMultiplayer.connected);await p.locator('#mp-name').fill('Тест '+(i+1));}
await pages[0].waitForFunction(n=>DustMultiplayer.players.length===n,n);for(const p of pages)await p.locator('#mp-start').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>DustMultiplayer.running&&__game.state.race.phase==='racing')));await Promise.all(pages.map(p=>p.keyboard.down('z')));await pages[0].waitForTimeout(3500);
for(const p of pages){const s=await p.evaluate(()=>({humans:DustMultiplayer.players.length,remotes:DustMultiplayer.remotes.map(r=>({id:r.id,bot:r.bot,x:r.x})),dots:[...document.querySelectorAll('.racer-dot')].map(x=>({id:x.dataset.id,left:x.style.left,title:x.title})),x:__game.state.race.player.x,field:document.querySelector('#field-size').textContent}));assert.equal(s.humans,n);assert.equal(s.remotes.length,3);assert.equal(s.remotes.filter(r=>r.bot).length,4-n);assert.equal(s.dots.length,n);assert(s.x>0);assert(s.remotes.every(r=>r.x>0));assert.equal(s.field,'4');assert(s.dots.every(d=>!s.remotes.some(r=>r.bot&&r.id===d.id)));}
await pages[0].screenshot({path:`/home/anton/.cache/dust-turbo-test/online-${n}-humans.png`});
// Finish humans without waiting a minute; authoritative bots must still finish themselves.
for(const p of pages)await p.evaluate(()=>{const r=__game.state.race;r.player.x=r.course.length-1;r.player.speed=1500;});
await Promise.all(pages.map(p=>p.waitForFunction(()=>DustMultiplayer.results?.length===4,null,{timeout:180000})));
const results=await pages[0].evaluate(()=>DustMultiplayer.results);for(const p of pages)assert.deepEqual(await p.evaluate(()=>DustMultiplayer.results),results);assert.equal(results.filter(r=>r.bot||r.name.includes('БОТ')).length,4-n);await pages[0].locator('#mp-results-room').click();await pages[0].locator('#mp-exit').click();assert.equal(await pages[0].evaluate(()=>DustMultiplayer.active),false);await pages[0].waitForTimeout(1000);assert.equal(await pages[0].evaluate(()=>DustMultiplayer.active),false);console.log(`PASS real ${n} humans + ${4-n} bots: moving riders, human-only dots, common four results, exit`);
}finally{for(const c of contexts)await c.close();await new Promise(r=>setTimeout(r,1000));}}
assert.deepEqual(errors,[]);console.log('PASS no browser errors');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
