const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const root=require('node:path').resolve(__dirname,'..');
function server(){const timers=[];const ctx={console,Date,crypto:require('node:crypto').webcrypto,setTimeout:f=>(timers.push(f),f),clearTimeout(){},setInterval:()=>1,clearInterval(){}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(root+'/core.js','utf8'),ctx);vm.runInContext(fs.readFileSync(root+'/worker/server.js','utf8').replace("import './core.js';",'').replace('export default','const worker =').replace('export class Lobby','class Lobby')+'\nglobalThis.Lobby=Lobby;',ctx);return {l:new ctx.Lobby({}),timers};}
for(const humans of [2,3,4]){const {l,timers}=server();l.players=Array.from({length:humans},(_,slot)=>({id:'h'+slot,slot,ready:true}));const events=[];l.broadcast=d=>events.push(d);l.evaluate();assert.equal(l.phase,'countdown');assert(l.at-Date.now()>=2900);timers[0]();assert.equal(l.bots.length,4-humans);assert.equal(l.players.length,humans);assert(events.some(e=>e.t==='start'));assert.equal(events.filter(e=>e.t==='state').length,4-humans);for(const b of l.bots){assert.equal(b.sim.player,b.p);assert.equal(b.sim.opponents.length,0);assert.equal(b.p.name,'БОТ');}l.results=Object.fromEntries(l.players.map(p=>[p.id,{id:p.id,time:2}]));l.finish();if(humans<4)assert.equal(l.phase,'racing');for(const b of l.bots){b.p.finished=true;b.p.finishTime=5;}l.stepBots();assert.equal(l.phase,'waiting');assert.equal(events.find(e=>e.t==='results').results.length,4);}
{const {l,timers}=server();l.players=[{id:'a',slot:0,ready:true}];l.evaluate();assert.equal(l.phase,'waiting');assert.equal(timers.length,0);}
// Browser harness: sender clocks cannot influence interpolation, canonical state stays intact.
let clock=10000;const elements=new Map(),timeouts=[];const elem=id=>{if(!elements.has(id))elements.set(id,{value:'Test',classList:{add(){},remove(){}},replaceChildren(){},setAttribute(){},addEventListener(){},append(){}});return elements.get(id);};
class WS{constructor(){WS.last=this;this.readyState=1;}send(){}close(){this.readyState=3;}}
const ctx={window:{},document:{getElementById:elem,createElement:()=>({append(){}})},WebSocket:WS,performance:{timeOrigin:0,now:()=>clock},localStorage:{getItem(){},setItem(){}},setInterval:()=>1,clearInterval(){},setTimeout:f=>(timeouts.push(f),f),clearTimeout(){}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(root+'/multiplayer.js','utf8'),ctx);const M=ctx.window.DustMultiplayer;
M.init({interrupt(){},wake(){},start(){},remote(){},player(){},home(){}});elem('friend').onclick();let ws=WS.last;const msg=d=>ws.onmessage({data:JSON.stringify({v:2,...d})});msg({t:'welcome',id:'me',now:clock});msg({t:'room',players:[{id:'me',slot:0},{id:'other',slot:1,name:'Other'}],waiting:[],phase:'racing',online:2});msg({t:'start',ids:['me'],at:clock,round:1,course:0});
const p=M.snapshot({x:0,lane:0,speed:1550,z:30,angle:0,airborne:true});msg({t:'state',id:'other',round:1,seq:1,at:10000,p});msg({t:'state',id:'other',round:1,seq:2,at:10100,p:{...p,x:155,lane:1,z:0,angle:1,airborne:false,crash:2}});
clock=10175;let rendered=M.renderRemotes()[0];assert.equal(rendered.x,77.5);assert.equal(rendered.lane,.5);assert.equal(rendered.z,15);assert.equal(rendered.angle,.5);assert.equal(rendered.airborne,true);assert.equal(rendered.crash,0);assert.equal(M.remotes[0].x,155);
msg({t:'state',id:'other',round:1,seq:1,at:10200,p:{...p,x:999}});assert.equal(M.remotes[0].x,155);
msg({t:'state',id:'other',round:1,seq:3,at:10200,p:{...p,x:310,airborne:false}});clock=11000;assert.equal(M.renderRemotes()[0].x,434);clock=12000;assert.equal(M.renderRemotes()[0].x,434);assert.equal(M.remotes[0].x,310);
ws.onclose();assert(!M.connected);assert(timeouts.length);timeouts.at(-1)();assert.notEqual(WS.last,ws);M.leave();assert(!M.active);
console.log('PASS network: readiness/countdown, 2/3/4 humans+server bots, results, canonical/render isolation, clocks, interpolation, stale cap, reconnect');
