export default {async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/health')return Response.json({ok:true,service:'dust-turbo',capacity:4,version:'ready-v3'});if(u.pathname!=='/ws'||request.headers.get('Upgrade')?.toLowerCase()!=='websocket')return new Response('Not found',{status:404});const origin=request.headers.get('Origin');if(origin&&origin!=='https://samsonovss.github.io'&&!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin))return new Response('Origin rejected',{status:403});return env.LOBBY.get(env.LOBBY.idFromName('public-ready-v3')).fetch(request);}};
const nameOf=s=>typeof s==='string'?s.normalize('NFKC').replace(/[\p{C}<>]/gu,'').trim().slice(0,20)||'Гонщик':'Гонщик';
export class Lobby {
 constructor(ctx){this.ctx=ctx;this.clients=new Map();this.players=[];this.phase='waiting';this.round=0;this.results={};this.at=0;}
 send(ws,d){try{ws.send(JSON.stringify({v:2,...d}));}catch{}}
 broadcast(d){for(const c of this.clients.values())if(c.joined)this.send(c.ws,d);}
 info(){this.broadcast({t:'room',id:'public',phase:this.phase,at:this.at,round:this.round,players:this.players.map(c=>({id:c.id,name:c.name,slot:c.slot,ready:c.ready})),waiting:[...this.clients.values()].filter(c=>c.joined&&!this.players.includes(c)).map(c=>({id:c.id,name:c.name})),online:[...this.clients.values()].filter(c=>c.joined).length});}
 eligible(){return this.players.length>=2&&this.players.every(c=>c.ready);}
 cancel(){clearTimeout(this.countdown);this.countdown=null;if(this.phase==='countdown'){this.phase='waiting';this.at=0;}}
 evaluate(){if(this.phase==='racing')return;if(!this.eligible())this.cancel();else if(this.phase==='waiting'){this.phase='countdown';this.at=Date.now()+3000;this.countdown=setTimeout(()=>{if(this.phase!=='countdown'||!this.eligible())return;this.phase='racing';this.round++;this.results={};for(const c of this.players)c.seq=-1;this.broadcast({t:'start',at:this.at,round:this.round,course:0,ids:this.players.map(c=>c.id)});this.info();},3000);}this.info();}
 fill(){if(this.phase==='racing')return;for(const c of this.clients.values())if(c.joined&&!this.players.includes(c)&&this.players.length<4){c.ready=false;c.slot=[0,1,2,3].find(n=>!this.players.some(p=>p.slot===n));this.players.push(c);}this.evaluate();}
 reset(){this.cancel();this.phase='waiting';this.at=0;for(const c of this.players)c.ready=false;this.fill();}
 finish(){if(this.phase==='racing'&&this.players.every(c=>this.results[c.id])){this.broadcast({t:'results',round:this.round,results:Object.values(this.results).sort((a,b)=>a.time-b.time)});this.reset();}}
 leave(c){if(!this.clients.has(c.ws))return;if(this.phase==='countdown'&&this.players.includes(c)){this.cancel();for(const p of this.players)p.ready=false;}this.clients.delete(c.ws);this.players=this.players.filter(p=>p!==c);this.finish();this.fill();this.info();}
 async fetch(){if(this.clients.size>=128)return new Response('Busy',{status:503});const pair=new WebSocketPair(),ws=pair[1];ws.accept();const c={id:crypto.randomUUID(),ws,name:'Гонщик',joined:false,ready:false,last:Date.now(),window:Date.now(),count:0,seq:-1};this.clients.set(ws,c);this.send(ws,{t:'welcome',id:c.id,now:Date.now()});ws.addEventListener('message',e=>{try{if(typeof e.data!=='string'||e.data.length>4096)return ws.close(1009,'Too large');const now=Date.now();if(now-c.window>1000){c.window=now;c.count=0;}if(++c.count>50)return ws.close(1008,'Rate');const d=JSON.parse(e.data);if(d.v!==2)return;c.last=now;if(d.t==='ping'){if(Number.isFinite(d.at))this.send(ws,{t:'pong',at:d.at,now});return;}if(d.t==='leave'){this.leave(c);ws.close(1000);return;}if(d.t==='join'){if(c.joined)return;c.name=nameOf(d.name);c.joined=true;this.fill();this.info();return;}if(!c.joined)return;if(d.t==='rename'){c.name=nameOf(d.name);this.info();return;}if(!this.players.includes(c))return;if(d.t==='ready'&&this.phase!=='racing'&&typeof d.ready==='boolean'){c.ready=d.ready;this.evaluate();return;}if(d.t==='state'&&this.phase==='racing'&&d.round===this.round&&Number.isSafeInteger(d.seq)&&d.seq>c.seq){const p=d.p;const limits={x:[0,1000000],lane:[0,3],targetLane:[0,3],speed:[0,10000],z:[-1000,10000],vz:[-10000,10000],angle:[-100000,100000],angular:[-10000,10000],heat:[0,10000],crash:[0,10000],crashes:[0,100000],finishTime:[0,3600],bump:[-10000,10000]};if(!p||!Object.entries(limits).every(([k,[lo,hi]])=>Number.isFinite(p[k])&&p[k]>=lo&&p[k]<=hi))return;const clean={};for(const k in limits)clean[k]=p[k];for(const k of ['airborne','boosting','finished','overheat'])clean[k]=p[k]===true;c.seq=d.seq;this.broadcast({t:'state',id:c.id,round:this.round,seq:d.seq,p:clean});if(clean.finished&&!this.results[c.id]&&now>=this.at){this.results[c.id]={id:c.id,name:c.name,time:Math.max(0,(now-this.at)/1000),crashes:clean.crashes};this.finish();}return;}if(d.t==='hidden'&&this.phase==='racing'){this.broadcast({t:'interrupted',message:c.name+' свернул игру. Готовность сброшена.'});this.reset();}}catch{}});const close=()=>this.leave(c);ws.addEventListener('close',close);ws.addEventListener('error',close);if(!this.timer)this.timer=setInterval(()=>{const now=Date.now();for(const c of this.clients.values())if(now-c.last>20000){this.leave(c);try{c.ws.close(1001,'Timeout');}catch{}}if(!this.clients.size){clearInterval(this.timer);this.timer=null;}},5000);return new Response(null,{status:101,webSocket:pair[0]});}
}
